// For this you will need the VS Code extension 'REST Client'
// Separate requests with tipple hashtags 
GET http://localhost:3000/devices

###
GET http://localhost:3000/devices/5f5fb0de6306722248074ff4

###

// make sure tp leave a blank line underneath
// Conten-Type: application/json
// or else you will get errors
POST http://localhost:3000/devices
Content-Type: application/json 

{
    "name": "Raspberry Pi 7",
    "location": "Lebanon",
    "energyOutput": 8
}

###
DELETE http://localhost:3000/devices/5f5faddf0e82b127b0ed89d3

###
PATCH http://localhost:3000/devices/5f5fb0de6306722248074ff4
Content-Type: application/json

{
    "name": "Pi 9"
}